import { createId } from '@domain/rating/rating.validation';
import {
  answeredTurns,
  beginAssistantRequest,
  clearPendingRequest,
  commitAnswer,
  isCandidateFresh,
  replaceQuestion,
  requestSnapshot,
  setConversationStatus,
  setQuestion,
  skipQuestion,
  startConversation,
  storeCandidate,
} from '@domain/writing/writing.machine';
import type {
  AssistantCandidate,
  AssistantOperation,
  TextOperation,
  WritingDraft,
} from '@domain/writing/writing.types';
import type { DiaryEntry } from '@domain/diary/diary.types';
import { AssistantError, type AssistantRequest } from '../gateway/assistant.gateway';
import { assistantGateway } from '../gateway/assistantGateway.instance';
import { useWritingStore } from './writing.store';

/**
 * Everything the assistant can be asked to do (spec §13, §15, §20).
 *
 * Two rules hold for every operation here:
 *  — the user's text is never replaced by a result, only offered beside it;
 *  — a failure leaves the draft exactly as it was, and says so.
 */

/** The rating the text belongs to, so a result never contradicts it. */
const ratingContext = (entry: DiaryEntry): AssistantRequest['rating'] => ({
  mode: entry.mode,
  overallRating: entry.overallRating,
  preciseRating: entry.preciseRating,
  ...(entry.mode === 'deep' ? { aspects: { ...entry.aspects } } : {}),
});

const filmContext = (draft: WritingDraft): AssistantRequest['film'] => ({
  filmId: draft.filmId,
  title: draft.film.filmTitle,
  year: draft.film.releaseYear,
});

/** Answered turns only: a skipped question carries no words to work from. */
const conversationContext = (draft: WritingDraft): AssistantRequest['conversation'] => {
  const conversation = draft.conversation;
  if (!conversation) return undefined;

  return {
    sessionId: conversation.sessionId,
    turns: answeredTurns(draft).map((turn) => ({
      questionId: turn.questionId,
      questionText: turn.questionText,
      answerText: turn.answerText,
    })),
    askedQuestionIds: [
      ...conversation.turns.map((turn) => turn.questionId),
      ...conversation.replacedQuestionIds,
    ],
    topics: conversation.selectedTopics,
  };
};

/*
 * Two lanes, because a question and a text operation are different intents: a
 * new question replaces the previous question, but composing a text must not
 * cancel — or be cancelled by — a question that happens to be in the air.
 */
type Lane = 'question' | 'text';
const inFlight: Record<Lane, AbortController | null> = { question: null, text: null };

const laneOf = (operation: AssistantOperation): Lane =>
  operation === 'nextQuestion' || operation === 'replaceQuestion' ? 'question' : 'text';

/** Anything in the air is abandoned: its result would answer an old question. */
export const cancelAssistant = (): void => {
  inFlight.question?.abort();
  inFlight.text?.abort();
  inFlight.question = null;
  inFlight.text = null;
  const store = useWritingStore.getState();
  store.setAssistantBusy(false);
  if (store.draft?.pendingAssistantRequest) {
    void store.apply(clearPendingRequest).catch(() => undefined);
  }
};

interface RunOptions {
  entry: DiaryEntry;
  operation: AssistantOperation;
  /** Generated by the caller, so a failure can be attributed to it. */
  requestId: string;
  text?: string;
  selection?: { start: number; end: number };
}

/**
 * Sends one request and returns the result, having recorded what was asked.
 * Throws AssistantError; the caller decides what the user sees.
 */
const run = async (options: RunOptions) => {
  const store = useWritingStore.getState();
  const draft = store.draft;
  if (!draft) throw new AssistantError('invalidRequest');

  const { requestId } = options;
  const lane = laneOf(options.operation);

  /*
   * Only a text operation is recorded in the draft. The marker is a single
   * slot, and a question request writing into it would overwrite the marker of
   * a text operation started a moment earlier — whose answer would then be
   * dropped as stale. Questions carry their own id in the closure instead.
   */
  if (lane === 'text') {
    const snapshot = requestSnapshot(draft, options.operation, requestId);
    await store.apply((current) => beginAssistantRequest(current, snapshot)).catch(() => undefined);
  }
  store.setAssistantBusy(true);
  inFlight[lane]?.abort();
  const controller = new AbortController();
  inFlight[lane] = controller;

  try {
    return await assistantGateway().send({
      requestId,
      operation: options.operation,
      film: filmContext(draft),
      rating: ratingContext(options.entry),
      ...(options.text === undefined ? {} : { text: options.text }),
      ...(options.selection ? { selection: options.selection } : {}),
      ...(conversationContext(draft) ? { conversation: conversationContext(draft) } : {}),
      signal: controller.signal,
    });
  } finally {
    if (inFlight[lane] === controller) inFlight[lane] = null;
    useWritingStore.getState().setAssistantBusy(false);
  }
};

/* --- conversation ------------------------------------------------------ */

/**
 * Guards against a second question request while one is already going out.
 * The draft is only marked "pending" after an await, and the conversation
 * screen reacts to every commit — without this, one question could become an
 * endless stream of them.
 */
let askingQuestion = false;

/** The question request whose answer is still wanted. */
let latestQuestionRequestId: string | null = null;

export const askNextQuestion = async (entry: DiaryEntry, replace = false): Promise<void> => {
  if (askingQuestion) return;
  askingQuestion = true;

  const store = useWritingStore.getState();
  // Set before anything awaits, so the UI cannot ask again in the gap.
  store.setAssistantBusy(true);
  await store.apply(startConversation).catch(() => undefined);
  useWritingStore.getState().setAssistantError(null);
  await store
    .apply((draft) =>
      setConversationStatus(replace ? replaceQuestion(draft) : draft, 'loadingQuestion'),
    )
    .catch(() => undefined);

  const requestId = createId();
  latestQuestionRequestId = requestId;
  try {
    const result = await run({
      entry,
      requestId,
      operation: replace ? 'replaceQuestion' : 'nextQuestion',
    });
    if (result.kind !== 'question') throw new AssistantError('unknown');

    // A question that answers a request nobody is waiting for is stale.
    if (latestQuestionRequestId !== requestId) return;
    await useWritingStore.getState().apply((draft) => setQuestion(draft, result.question));
    useWritingStore.getState().setAssistantError(null);
  } catch (error) {
    await failed(error, requestId, replace ? 'replaceQuestion' : 'nextQuestion');
  } finally {
    askingQuestion = false;
    useWritingStore.getState().setAssistantBusy(false);
  }
};

/** The user's exact words are stored first — before any request goes out. */
export const answerQuestion = async (entry: DiaryEntry, answer: string): Promise<void> => {
  await useWritingStore.getState().apply((draft) => commitAnswer(draft, answer));
  await askNextQuestion(entry);
};

export const skipCurrentQuestion = async (entry: DiaryEntry): Promise<void> => {
  await useWritingStore.getState().apply(skipQuestion);
  await askNextQuestion(entry);
};

/* --- text operations ---------------------------------------------------- */

export interface TextOperationOptions {
  entry: DiaryEntry;
  operation: TextOperation;
  selection?: { start: number; end: number };
  requestId?: string;
}

/**
 * Produces a candidate. The working text is untouched until the user accepts
 * it: SYO proposes, the user decides (spec §2.2).
 */
export const runTextOperation = async (options: TextOperationOptions): Promise<void> => {
  const draft = useWritingStore.getState().draft;
  if (!draft) return;

  // 'collect' builds a text out of the conversation; the rest transform one.
  const text = options.operation === 'collect' ? undefined : draft.workingText;
  // A retry reuses the id, so it is the same logical request, not a second one.
  const requestId = options.requestId ?? createId();

  try {
    const result = await run({
      entry: options.entry,
      operation: options.operation,
      requestId,
      ...(text === undefined ? {} : { text }),
      ...(options.selection ? { selection: options.selection } : {}),
    });
    if (result.kind !== 'text') throw new AssistantError('unknown');

    const candidate: AssistantCandidate = {
      id: createId(),
      baseRevisionId: draft.selectedRevisionId,
      operation: result.operation,
      text: result.text,
      changeSummary: result.changeSummary,
      promptVersion: result.promptVersion,
      requestId: result.requestId,
      createdAt: new Date().toISOString(),
    };

    await useWritingStore.getState().apply((current) => {
      // A late response to a request the user has moved past is dropped.
      if (!isCandidateFresh(current, candidate)) return current;
      return storeCandidate(current, candidate);
    });
    useWritingStore.getState().setAssistantError(null);
  } catch (error) {
    await failed(error, requestId, options.operation);
  }
};

/** Builds the text out of the answers already given. */
export const composeFromConversation = (entry: DiaryEntry): Promise<void> =>
  runTextOperation({ entry, operation: 'collect' });

/* --- failures ----------------------------------------------------------- */

/**
 * A failed request changes nothing about the draft. Only its *own* pending
 * marker is cleared: an abandoned request finishing later must not wipe the
 * marker of the request the user is now waiting for — the fresh answer would
 * then be dropped as stale.
 */
const failed = async (
  error: unknown,
  requestId: string,
  operation: AssistantOperation,
): Promise<void> => {
  const assistantError = error instanceof AssistantError ? error : new AssistantError('unknown');

  const store = useWritingStore.getState();
  // Only its own marker, never someone else's: a request abandoned long ago
  // must not clear the marker of the one the user is waiting for now.
  await store
    .apply((draft) =>
      draft.pendingAssistantRequest?.requestId === requestId ? clearPendingRequest(draft) : draft,
    )
    .catch(() => undefined);
  if (store.draft?.conversation) {
    // 'error' is what stops the conversation asking again on its own; the user
    // retries deliberately, and a dead network costs exactly one request.
    await store
      .apply((draft) =>
        setConversationStatus(draft, assistantError.code === 'cancelled' ? 'idle' : 'error'),
      )
      .catch(() => undefined);
  }
  // 'cancelled' is the user's own doing — never an error to explain.
  store.setAssistantError(assistantError.code === 'cancelled' ? null : assistantError, {
    operation,
    requestId,
  });
};
